-- CreateEnum
CREATE TYPE "AvatarSlot" AS ENUM ('SKIN_TONE', 'GLASSES', 'FACE_ACCESSORY', 'AURA', 'FRAME', 'HAIR', 'FACIAL_HAIR', 'HAT', 'HEADPHONES', 'BOW', 'HAIR_FLOWER', 'NECKLACE', 'EYELASHES', 'HEADBAND', 'CAT_EARS', 'CYBER_VISOR');

-- CreateEnum
CREATE TYPE "StoreGenderTab" AS ENUM ('UNISEX', 'MALE', 'FEMALE');

-- CreateEnum
CREATE TYPE "StoreRarity" AS ENUM ('COMMON', 'RARE', 'EPIC');
